name: Build-Release

on:
  push:
    tags:
      - "*"

jobs:
  platformio-build:
    runs-on: ubuntu-latest
    container: fishros2/ros2pio:humble

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build firmware
        run: /bin/bash release.sh $GITHUB_REF_NAME

      - name: Compress .pio directory
        run: |
          cd .pio/libdeps/featheresp32/micro_ros_platformio/
          zip -r libmicroros libmicroros

      - name: Generate file list for bin directory
        id: file_list
        run: |
          file_list=$(ls -1 bin/*.bin)
          echo "FILES=$file_list" >> $GITHUB_ENV

      - name: Create Release and Upload Release Asset  
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')  
        with:  
          tag_name: ${{ github.ref }}  
          name: $GITHUB_REF_NAME
          body_path: ${{ github.workspace }}/release-notes.md
          draft: false  
          prerelease: false  
          files: |  
            ${{ env.FILES }}  
            .pio/libdeps/featheresp32/micro_ros_platformio/libmicroros.zip
